### ISSUE TITLE
resort，VSCode build failed

### ISSUE THREAD

**Issue by gxh1996** [callanh/pathos-official#5]
Hi, thanks for this wonderful game :)

I am not very proficient in programming. After following your steps to install, the Ctrl+Shift+B build failed, causing a headache. Is there anything wrong? Can you help me? Thank you.

![image](https://github.com/callanh/pathos-official/assets/48506232/577ed913-9db0-4516-897d-41dbd7c4ddfe)

**Comment by callanh** [comment]
Hello! I'd say you need to use the self-update for the Windows Desktop version of Pathos. The code you have and the version of Pathos you have need to be the latest.

**Comment by gxh1996** [comment]
Great, problem solved. Thank you
